\c cs415

-- web_user
CREATE TABLE web_user (
    web_user_id INT GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR(25) NOT NULL,
    last_name VARCHAR(30) NOT NULL,
    email VARCHAR(40) UNIQUE NOT NULL,
    password VARCHAR(40) NOT NULL,
    created_date TIMESTAMP DEFAULT NULL,
    is_active BOOLEAN DEFAULT true,
    last_login TIMESTAMP DEFAULT NULL,
    PRIMARY KEY (web_user_id)
);

-- address_type
CREATE TABLE address_type (
    address_type_id INT GENERATED BY DEFAULT AS IDENTITY,
    address_type VARCHAR(20) NOT NULL,
    PRIMARY KEY (address_type_id)
);

-- user_address
CREATE TABLE user_address (
    user_address_id INT GENERATED BY DEFAULT AS IDENTITY,
    web_user_id INT NOT NULL,
    street_1 VARCHAR(50),
    street_2 VARCHAR(50),
    city VARCHAR(35),
    st VARCHAR(2),
    zip VARCHAR(10),
    country VARCHAR(30),
    created_date TIMESTAMP,
    address_type_id INT NOT NULL,
    PRIMARY KEY (user_address_id),
    FOREIGN KEY (web_user_id) REFERENCES web_user(web_user_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    FOREIGN KEY (address_type_id) REFERENCES address_type(address_type_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

-- phone_type
CREATE TABLE phone_type (
    phone_type_id INT GENERATED BY DEFAULT AS IDENTITY,
    phone_type VARCHAR(20) NOT NULL,
    PRIMARY KEY (phone_type_id)
);

-- user_phone
CREATE TABLE user_phone (
    user_phone_id INT GENERATED BY DEFAULT AS IDENTITY,
    web_user_id INT NOT NULL,
    phone_number VARCHAR(20) NOT NULL,
    phone_type_id INT NOT NULL,
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_phone_id),
    FOREIGN KEY (web_user_id) REFERENCES web_user(web_user_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    FOREIGN KEY (phone_type_id) REFERENCES phone_type(phone_type_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

-- user_info
CREATE TABLE user_info (
    user_info_id INT GENERATED BY DEFAULT AS IDENTITY,
    web_user_id INT NOT NULL,
    profile_bio TEXT,
    profile_picture VARCHAR(255),
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_info_id),
    FOREIGN KEY (web_user_id) REFERENCES web_user(web_user_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

-- page_data
CREATE TABLE page_data (
    page_data_id INT GENERATED BY DEFAULT AS IDENTITY,
    page_title VARCHAR(100) NOT NULL,
    page_subtitle VARCHAR(100),
    page_content TEXT,
    page_image VARCHAR(255),
    page_header VARCHAR(150),
    PRIMARY KEY (page_data_id)
);